# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  database: db/benkyou_development.sqlite3
  pool: 5
  username: root
  host: 127.0.0.1
